version: "3.3"
services:
  first-xest-project-db:
    container_name: first-xest-project-mysql-db
    image: jamielsharief/mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "first_xest_project_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - vol-first-xest-project-db:/var/lib/mysql
volumes:
  vol-first-xest-project-db:
